name: 'Learn'
description: 'Learn Action'
inputs:
  owner:
    description: 'Owner Description'
    required: true
  repo:
    description: 'Repo Name'
    required: true
  pr_number:
    description: 'Number of pull request'
    required: true
  token:
    description: 'Access Token'
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'
